application:
  workspace: LOCAL
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

database:
  url: jdbc:mariadb://localhost:3306/hbd_onf_hj
  username:
  password:

logging:
  lovel: DEBUG

firebase:
  path: "src/main/resources/"



