application:
  workspace: AWS
  port: 4022

spring:
  config:
    activate:
      on-profile: prod

database:
  url: jdbc:mariadb://localhost:3306/hbd_onf_hj
  username:
  password:

logging:
  lovel: INFO

firebase:
  path: "/usr/local/tomcat/webapps/"
