application:
  workspace: LOCAL
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

database:
  url: jdbc:mariadb://localhost:3306/hbd_onf_hj
  username: root
  password: root

logging:
  lovel: DEBUG

firebase:
  path: "src/main/resources/hbd-onf-firebase-adminsdk-7m49q-cd688bd5b0.json"



